[package]
name = "timeboxing"
version = "0.1.0"
description = "时间盒 TIMEBOXING"
edition = "2021"

[dependencies]
tauri = { version = "2", features = [] }

[build-dependencies]
tauri-build = { version = "2", features = [] }
